version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - data:/data
    command: server /data

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - minio

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  minio-exporter:
    image: quay.io/prometheus-community/minio-exporter
    ports:
      - 9689:9689
    environment:
      - MINIO_SERVER=http://minio:9000
    depends_on:
      - minio

volumes:
  data:
  grafana-data:
